### ISSUE TITLE
HU04-Servicio de Consulta de Aportes

### ISSUE THREAD

**Issue by ariasckm** [LuisDev18/IntegradorII#5]
Los socios pueden consultar sus aportes y ver detalles como fecha y monto.

**Comment by ariasckm** [comment]
- [ ] En el panel de usuario, debería haber una opción claramente visible que diga "Consulta de Aportes".
- [ ] Al hacer clic en "Consulta de Aportes", el socio debería ser redirigido a una página de consulta de aportes.
- [ ] En la página de consulta de aportes, se debe mostrar una tabla que agrupe los aportes por período en filas y por meses en columnas.
- [ ] Los meses deben estar etiquetados en la parte superior de la tabla.
- [x] Los datos de aportes deben ser recuperados desde la fecha de ingreso del socio al fondo hasta la fecha actual.
- [ ] Debe haber una opción para imprimir la consulta, que genere una versión imprimible de la tabla de aportes.
- [ ] Debe haber una opción para exportar la consulta en un formato descargable, como un archivo XLS o PDF.

![Image](https://github.com/LuisDev18/IntegradorII/assets/145524743/3abdc738-b379-4435-b483-77e492524d88)

**Comment by ariasckm** [comment]
Se utilizara la tabla tbl_aportaciones para la vista, a continuación el diccionario de datos de la tabla.

![Image](https://github.com/LuisDev18/IntegradorII/assets/145524743/ff2abdfb-b57b-4c6b-acbe-443df5211c9e)


En la vista a mostrar se utilizara el siguiente select:
select c_t_origen, n_i_anhio, 
n_n_aporte01, n_n_aporte02, n_n_aporte03, n_n_aporte04, n_n_aporte05, 
n_n_aporte06, n_n_aporte07, n_n_aporte08, n_n_aporte09, n_n_aporte10, 
n_n_aporte11, n_n_aporte12, n_n_total
from tbl_aportaciones
where c_t_cip = '322278000'
order by c_t_origen, n_i_anhio

**Comment by LuisDev18** [comment]
@migueltaipemamani Puedes utilizar los siguientes insert para agregar registro de data de prueba, tienes que asegurarte de que los usuarios existan primero en la tbl_clientes:


#INSERT DE DATOS PARA LA TABLA TBL_APORTACIONES:
INSERT INTO  tbl_aportaciones  ([c_t_origen]
           ,[n_n_aporte08]
           ,[n_n_aporte11]
           ,[n_n_aporte05]
           ,[n_n_aporte01]
           ,[n_n_aporte04]
           ,[n_n_aporte09]
           ,[n_n_aporte02]
           ,[n_n_aporte07]
           ,[n_n_aporte06]
           ,[n_n_aporte10]
           ,[n_n_aporte03]
           ,[n_n_total]
           ,[n_n_aporte12]
           ,[n_i_año]
           ,[c_t_cip]) VALUES
( 'DEVOLUCION DE APORTE', 125.00, 125.00, 125.00, 125.00, 125.00, 125.00, 125.00, 125.00, 125.00, 125.00, 125.00,1200, 125.00, 1999,123405221),
('ACTIVIDAD', 150.00, 135.00, 110.00, 125.00, 145.00, 120.00, 130.00, 140.00, 115.00, 155.00, 105.00, 1300, 165.00, 2000, 123405221),
('DEVOLUCION DE APORTE', 155.00, 120.00, 115.00, 130.00, 150.00, 125.00, 135.00, 145.00, 110.00, 160.00, 110.00, 1400, 160.00, 2001, 123405221),
('NIVELACION DE APORTE', 160.00, 125.00, 120.00, 135.00, 155.00, 130.00, 140.00, 150.00, 115.00, 165.00, 115.00, 1500, 155.00, 2002, 123405221),
('ACTIVIDAD', 165.00, 130.00, 125.00, 140.00, 160.00, 135.00, 145.00, 155.00, 120.00, 170.00, 120.00, 1600, 150.00, 2003, 123405221),
('DEVOLUCION DE APORTE', 170.00, 135.00, 130.00, 145.00, 165.00, 140.00, 150.00, 160.00, 125.00, 175.00, 125.00, 1700, 165.00, 2004, 123405221),
('NIVELACION DE APORTE', 175.00, 140.00, 135.00, 150.00, 170.00, 145.00, 155.00, 165.00, 130.00, 180.00, 130.00, 1800, 160.00, 2005, 123405221),
('ACTIVIDAD', 180.00, 145.00, 140.00, 155.00, 175.00, 150.00, 160.00, 170.00, 135.00, 185.00, 135.00, 1900, 165.00, 2006, 123405221),
('DEVOLUCION DE APORTE', 185.00, 150.00, 145.00, 160.00, 180.00, 155.00, 165.00, 175.00, 140.00, 190.00, 140.00, 2000, 170.00, 2007, 123405221),
('NIVELACION DE APORTES', 190.00, 155.00, 150.00, 165.00, 185.00, 160.00, 170.00, 180.00, 145.00, 195.00, 145.00, 2100, 175.00, 2008, 123405221),
('ACTIVIDAD', 195.00, 160.00, 155.00, 170.00, 190.00, 165.00, 175.00, 185.00, 150.00, 200.00, 150.00, 2200, 180.00, 2009, 123405221),
('DEVOLUCION DE APORTE', 200.00, 165.00, 160.00, 175.00, 195.00, 170.00, 180.00, 190.00, 155.00, 205.00, 155.00, 2300, 185.00, 2010, 123405221),
('NIVELACION DE APORTES', 205.00, 170.00, 165.00, 180.00, 200.00, 175.00, 185.00, 195.00, 160.00, 210.00, 160.00, 2400, 190.00, 2011, 123405221),
('ACTIVIDAD', 210.00, 175.00, 170.00, 185.00, 205.00, 180.00, 190.00, 200.00, 165.00, 215.00, 165.00, 2500, 195.00, 2012, 123405221),
('DEVOLUCION DE APORTE', 215.00, 180.00, 175.00, 190.00, 210.00, 185.00, 195.00, 205.00, 170.00, 220.00, 170.00, 2600, 200.00, 2013, 123405221),
('NIVELACION DE APORTES', 220.00, 185.00, 180.00, 195.00, 215.00, 190.00, 200.00, 210.00, 175.00, 225.00, 175.00, 2700, 205.00, 2014, 123405221),
('ACTIVIDAD', 225.00, 190.00, 185.00, 200.00, 220.00, 195.00, 205.00, 215.00, 180.00, 230.00, 180.00, 2800, 210.00, 2015, 123405221),
('DEVOLUCION DE APORTE', 230.00, 195.00, 190.00, 205.00, 225.00, 200.00, 210.00, 220.00, 185.00, 235.00, 185.00, 2900, 215.00, 2016, 123405221),
('NIVELACION DE APORTES', 235.00, 200.00, 195.00, 210.00, 230.00, 205.00, 215.00, 225.00, 190.00, 240.00, 190.00, 3000, 220.00, 2017, 123405221),
('ACTIVIDAD', 240.00, 205.00, 200.00, 215.00, 235.00, 210.00, 220.00, 230.00, 195.00, 245.00, 195.00, 3100, 225.00, 2018, 123405221),
('DEVOLUCION DE APORTE', 245.00, 210.00, 205.00, 220.00, 240.00, 215.00, 225.00, 235.00, 200.00, 250.00, 200.00, 3200, 230.00, 2019, 123405221),
('NIVELACION DE APORTES', 250.00, 215.00, 210.00, 225.00, 245.00, 220.00, 230.00, 240.00, 205.00, 255.00, 205.00, 3300, 235.00, 2020, 123405221);

('DEVOLUCION DE APORTE', 125.00, 125.00, 125.00, 125.00, 125.00, 125.00, 125.00, 125.00, 125.00, 125.00, 125.00,1200, 125.00, 2001,123405222);
